# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import intents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', intents.models.SingleLineTextField(unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Intent',
                'verbose_name_plural': 'Intents',
                'ordering': ('name',),
            },
        ),
    ]
