# Generated by Django 2.0 on 2017-12-04 23:13

from django.db import migrations, models
import django.db.models.deletion
import intents.models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_language'),
        ('intents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('text', intents.models.SingleLineTextField(verbose_name='Text')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='intents.Intent', verbose_name='Intent')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='countries.Language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ('text',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('text', 'language', 'intent')},
        ),
    ]
