# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import intents.models


class Migration(migrations.Migration):

    dependencies = [
        ('intents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('text', intents.models.SingleLineTextField(verbose_name='Text')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='intents.Intent', verbose_name='Intent')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ('text',),
            },
        ),
    ]
