# Generated by Django 2.0 on 2017-12-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0005_answer'),
        ('intents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='intents', to='texts.Answer', verbose_name='Answers'),
        ),
    ]
