# Generated by Django 2.0 on 2017-12-07 17:53

from django.db import migrations, models
import intents.models


class Migration(migrations.Migration):

    dependencies = [
        ('intents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('key', intents.models.SingleLineTextField(verbose_name='Key')),
                ('value', intents.models.SingleLineTextField(blank=True, null=True, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
                'ordering': ('key', 'value'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('key', 'value')},
        ),
    ]
