# Generated by Django 2.0 on 2017-12-08 18:03

import computer.fields
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLURequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Request parameters')),
                ('nlu_model_output', django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='NLU model output')),
                ('intent_output', django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Intent output')),
                ('answer', computer.fields.SingleLineTextField(verbose_name='Answer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nlu_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'NLU request',
                'verbose_name_plural': 'NLU requests',
                'ordering': ('user', '-updated_at'),
            },
        ),
    ]
