# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 11:56
from __future__ import unicode_literals

import computer.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', computer.fields.SingleLineTextField(unique=True, verbose_name='Name')),
                ('locale_name', computer.fields.SingleLineTextField(unique=True, verbose_name='Locale name')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='ISO code')),
                ('phone_prefix', models.CharField(max_length=5, unique=True, verbose_name='Phone prefix')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ('code',),
            },
        ),
    ]
