# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 11:59
from __future__ import unicode_literals

import computer.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', computer.fields.SingleLineTextField(unique=True, verbose_name='Name')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='ISO code')),
                ('countries', models.ManyToManyField(blank=True, related_name='languages', to='countries.Country', verbose_name='Countries')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ('name',),
            },
        ),
    ]
