# Generated by Django 5.1.11 on 2025-06-16 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("texts", "0002_trigger"),
    ]

    operations = [
        migrations.CreateModel(
            name="TriggerEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("start", models.PositiveIntegerField(verbose_name="Start")),
                ("end", models.PositiveIntegerField(verbose_name="End")),
                ("value", models.CharField(max_length=256, verbose_name="Value")),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="texts.entity",
                        verbose_name="Entity",
                    ),
                ),
                (
                    "trigger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="texts.trigger",
                        verbose_name="Trigger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trigger entity",
                "verbose_name_plural": "Trigger entities",
                "ordering": ("trigger", "start", "end"),
            },
        ),
    ]
