# Generated by Django 5.1.11 on 2025-06-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intents", "0001_initial"),
        ("texts", "0005_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="intent",
            name="answers",
            field=models.ManyToManyField(
                blank=True,
                related_name="intents",
                to="texts.answer",
                verbose_name="Answers",
            ),
        ),
    ]
