# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import texts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0002_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('content', texts.models.SingleLineTextField(verbose_name='Content')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='countries.Language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Text',
                'verbose_name_plural': 'Texts',
                'ordering': ('language',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='text',
            unique_together=set([('content', 'language')]),
        ),
    ]
