# Generated by Django 2.0 on 2017-12-08 12:50

import computer.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', computer.fields.SingleLineTextField(unique=True, verbose_name='Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='children', to='texts.Entity', verbose_name='Parent'))
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'ordering': ('name',),
            },
        ),
    ]
