# Generated by Django 2.0 on 2017-12-08 12:54

from django.db import migrations, models
import computer.fields
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intents', '0001_initial'),
        ('countries', '0002_language'),
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('text', computer.fields.SingleLineTextField(verbose_name='Text')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='intents.Intent', verbose_name='Intent')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='countries.Language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Trigger',
                'verbose_name_plural': 'Triggers',
                'ordering': ('language',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='trigger',
            unique_together={('text', 'language')},
        ),
    ]
