# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import texts.models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', texts.models.SingleLineTextField(unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'ordering': ('name',),
            },
        ),
    ]
