# Generated by Django 2.0 on 2017-12-08 13:00

from django.db import migrations, models
import computer.fields
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_triggers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('start', models.PositiveIntegerField(verbose_name='Start')),
                ('end', models.PositiveIntegerField(verbose_name='End')),
                ('value', computer.fields.SingleLineTextField(verbose_name='Value')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='texts.Entity', verbose_name='Entity')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='texts.Trigger', verbose_name='Trigger')),
            ],
            options={
                'verbose_name': 'Trigger entity',
                'verbose_name_plural': 'Trigger entities',
                'ordering': ('trigger', 'start', 'end'),
            },
        ),
    ]
