# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import texts.models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('start', models.PositiveIntegerField(verbose_name='Start')),
                ('end', models.PositiveIntegerField(verbose_name='End')),
                ('value', texts.models.SingleLineTextField(verbose_name='Value')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='texts.Entity', verbose_name='Entity')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='texts.Text', verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Text entity',
                'verbose_name_plural': 'Text entities',
                'ordering': ('text', 'start', 'end'),
            },
        ),
    ]
