# Generated by Django 2.0 on 2017-12-08 13:14

import computer.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_triggerentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('key', computer.fields.SingleLineTextField(verbose_name='Key')),
                ('value', computer.fields.SingleLineTextField(blank=True, null=True, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
                'ordering': ('key', 'value'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('key', 'value')},
        ),
    ]
