# Generated by Django 2.0 on 2017-12-08 13:24

from django.db import migrations, models
import computer.fields
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_language'),
        ('texts', '0004_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('text', computer.fields.SingleLineTextField(verbose_name='Text')),
                ('attributes', models.ManyToManyField(blank=True, related_name='answers', to='texts.Attribute', verbose_name='Attributes')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='countries.Language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ('language',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('text', 'language')},
        ),
    ]
